"""Proposed training curriculum.

STATUS: PROPOSED. Declared as data so that the ordering can be argued with, and so
that a stage cannot quietly start before its inputs exist.

Revision of the sequence in the Step 5 brief
--------------------------------------------

The brief proposed nine stages. Six are proposed instead, and three changes are
deliberate:

1. **Text-to-anatomy is merged with text-anatomy alignment.** They share data,
   they share a model, and splitting them creates a checkpoint nobody uses.
2. **Anatomy-to-geometry correspondence is merged into geometry autoencoding.**
   The part-label head is trained with reconstruction; separating them invites a
   representation that reconstructs well and labels badly, which is the exact
   failure the project is trying to avoid.
3. **Images move to the end and become optional.** They are the hardest modality
   to licence and the only one that is not required for text-only inference. The
   first two stages need no external data at all, which means work can begin
   before any dataset decision is settled. That de-risks the schedule more than
   any modelling choice in this document.

Animation stays last, because it needs temporal data that does not exist yet, and
because a wrong cardiac cycle on a wrong heart teaches nothing.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

from awr.errors import ContractError
from generation.neural.losses import LOSSES, LossSpec, loss

__all__ = ["CurriculumStage", "CURRICULUM", "stage", "validate_curriculum"]


@dataclass(frozen=True, slots=True)
class CurriculumStage:
    """One stage of the proposed curriculum."""

    key: str
    title: str
    goal: str
    inputs: tuple[str, ...]
    objectives: tuple[str, ...]
    trains: tuple[str, ...]
    frozen: tuple[str, ...]
    exit_criteria: tuple[str, ...]
    external_data_required: bool
    blocked_by: tuple[str, ...] = ()
    status: str = "PROPOSED"

    def objective_specs(self) -> tuple[LossSpec, ...]:
        """Loss specifications for this stage."""
        return tuple(loss(name) for name in self.objectives)


CURRICULUM: tuple[CurriculumStage, ...] = (
    CurriculumStage(
        key="S0",
        title="Ontology self-supervised pretraining",
        goal=(
            "Teach the entity and graph encoders what the anatomy is, before any geometry or "
            "language is involved."
        ),
        inputs=("Heart Ontology v0.1 only. No external data.",),
        objectives=(
            "entity_identity",
            "structural_relationship",
            "spatial_relationship",
            "functional_relationship",
        ),
        trains=("entity embedding table", "graph encoder", "entity prototypes"),
        frozen=(),
        exit_criteria=(
            "Held-out edge prediction is well above the frequency baseline on all three graphs.",
            "Sibling entities are separable in the alignment space.",
        ),
        external_data_required=False,
    ),
    CurriculumStage(
        key="S1",
        title="Language to AWR program",
        goal="Map utterances to verifiable programs over the closed entity codebook.",
        inputs=(
            "Utterance and program pairs generated by the Step 4 transcoder, with paraphrase "
            "and synonym augmentation drawn from the ontology.",
        ),
        objectives=("language_anatomy_alignment", "entity_identity"),
        trains=("language encoder", "pointer head", "text projection"),
        frozen=("entity embedding table",),
        exit_criteria=(
            "Program accuracy on held-out paraphrases exceeds the rule parser's coverage.",
            "No predicted entity argument falls outside the codebook, which is structural.",
        ),
        external_data_required=False,
        blocked_by=("S0",),
    ),
    CurriculumStage(
        key="S2",
        title="Geometry autoencoding with part supervision",
        goal=(
            "Learn per-entity geometry tokens that reconstruct shape, carry part labels and "
            "behave under level of detail."
        ),
        inputs=(
            "Part-labelled 3D hearts: the synthetic tier first, then licensed real data.",
        ),
        objectives=(
            "geometry_reconstruction",
            "semantic_part_correspondence",
            "entity_frame",
            "lod_consistency",
        ),
        trains=("geometry tokeniser", "per-entity field decoder", "frame head", "part head"),
        frozen=("entity embedding table", "graph encoder"),
        exit_criteria=(
            "Reconstruction is close enough that generation error is not dominated by the "
            "autoencoder.",
            "Part labels are near-perfect on the synthetic tier, where they are exact.",
            "Decoding at every token prefix yields the same structure at different detail.",
        ),
        external_data_required=True,
        blocked_by=("S0",),
    ),
    CurriculumStage(
        key="S3",
        title="AWR to geometry generation",
        goal="Generate geometry tokens from the anatomical latent rather than encoding them.",
        inputs=("The same 3D corpus, now used as generation targets conditioned on the AWR.",),
        objectives=(
            "geometry_reconstruction",
            "semantic_part_correspondence",
            "entity_frame",
            "lod_consistency",
        ),
        trains=("anatomical encoder", "token generator"),
        frozen=("field decoder (initially)", "entity embedding table"),
        exit_criteria=(
            "Generated scenes satisfy held-out relationship checks better than the baseline.",
            "Geometry quality is within a stated tolerance of the S2 autoencoder.",
        ),
        external_data_required=True,
        blocked_by=("S1", "S2"),
    ),
    CurriculumStage(
        key="S4",
        title="Persistent editing",
        goal="Edit one entity without disturbing the others.",
        inputs=(
            "Before and after scene pairs with edit instructions, generated by the Step 4 "
            "engine over the same corpus.",
        ),
        objectives=("edit_consistency", "geometry_reconstruction"),
        trains=("local editor", "edit conditioning"),
        frozen=("anatomical encoder", "field decoder"),
        exit_criteria=(
            "Untouched token blocks are bit-identical, which is checked exactly rather than "
            "with a tolerance.",
            "The edited entity matches its target as well as a freshly generated one.",
        ),
        external_data_required=True,
        blocked_by=("S3",),
    ),
    CurriculumStage(
        key="S5",
        title="Optional modalities: images, multi-view, animation",
        goal="Add image grounding and temporal behaviour once the core loop works.",
        inputs=(
            "Licensed entity-labelled images and multi-view renders; temporal 3D data for the "
            "cardiac cycle. None of this is acquired yet.",
        ),
        objectives=(
            "cross_modal_alignment",
            "style_invariance",
            "multi_view_consistency",
            "functional_animation_consistency",
        ),
        trains=("image encoder", "animation decoder"),
        frozen=("entity prototypes", "anatomical encoder"),
        exit_criteria=(
            "Image retrieval against entity prototypes is accurate on held-out styles.",
            "Animated scenes preserve the flow circuit across every phase.",
        ),
        external_data_required=True,
        blocked_by=("S3",),
    ),
)
"""The proposed six-stage curriculum."""


def stage(key: str) -> CurriculumStage:
    """Return one stage by key."""
    for candidate in CURRICULUM:
        if candidate.key == key:
            return candidate
    raise ContractError(
        f"Unknown curriculum stage {key!r}. Declared: {', '.join(s.key for s in CURRICULUM)}."
    )


def validate_curriculum(stages: Sequence[CurriculumStage] | None = None) -> None:
    """Check the curriculum is consistent and acyclic.

    Three checks, each guarding a mistake that is cheap to make and expensive to
    discover during training: an objective that does not exist, a stage that
    depends on a later stage, and an objective used in a stage its own
    declaration does not list.
    """
    active = tuple(stages or CURRICULUM)
    keys = [s.key for s in active]
    if len(set(keys)) != len(keys):
        raise ContractError("Curriculum stage keys must be unique.")
    known_losses = {spec.name: spec for spec in LOSSES}
    position = {key: index for index, key in enumerate(keys)}
    for current in active:
        for objective in current.objectives:
            if objective not in known_losses:
                raise ContractError(
                    f"Stage {current.key} uses undeclared objective {objective!r}."
                )
            if current.key not in known_losses[objective].stages:
                raise ContractError(
                    f"Objective {objective!r} is used by stage {current.key} but does not list "
                    "it among its stages. One of the two declarations is wrong."
                )
        for dependency in current.blocked_by:
            if dependency not in position:
                raise ContractError(
                    f"Stage {current.key} depends on unknown stage {dependency!r}."
                )
            if position[dependency] >= position[current.key]:
                raise ContractError(
                    f"Stage {current.key} depends on {dependency!r}, which does not come before it."
                )


validate_curriculum()


def stages_without_external_data() -> tuple[str, ...]:
    """Stages that can start today, with no dataset and no licensing exposure."""
    return tuple(s.key for s in CURRICULUM if not s.external_data_required)
