"""The proposed Lagnav model, as a composition of declared stages.

STATUS: skeleton. The pipeline, its stages and their contracts are declared and
checked; no stage computes anything, and no framework is imported.

What this module is for
-----------------------

Two things that are worth having before a line of model code exists:

1. **A composition check.** :meth:`LagnavArchitecture.validate` proves every
   stage's inputs are produced by an earlier stage or supplied with the batch. A
   pipeline that does not compose on paper will not compose in a framework.
2. **A shape trace.** :func:`trace_pipeline` walks the whole pipeline with a real
   AWR batch at the front and resolved shapes everywhere after it, which is the
   closest thing to a forward pass that is honest at this stage. It catches the
   errors that are expensive later: a dimension meaning two things, a stage
   expecting a tensor nobody emits.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field

from awr.errors import ContractError
from awr.ontology import AnatomyOntology
from awr.scene import AWRScene
from generation.neural.anatomical_encoder import (
    SCENE_CONTEXT_CONTRACT,
    AnatomicalEncoderSpec,
    AnatomicalReasoningEncoder,
)
from generation.neural.contracts import CONTRACTS, Contract, PlainArray
from generation.neural.features import AWR_BATCH_CONTRACT, AWRFeatureExtractor
from generation.neural.graph_encoder import (
    GRAPH_ENCODER_CONTRACT,
    AnatomicalGraphEncoder,
    GraphEncoderSpec,
)
from generation.neural.language_encoder import (
    PROGRAM_CONTRACT,
    TEXT_CONTRACT,
    ConditioningLanguageEncoder,
    LanguageEncoderSpec,
    TextToProgramModel,
)
from generation.neural.latent import LATENT_CONTRACT
from generation.neural.multimodal import ALIGNMENT_CONTRACT, ModalityEncoder
from generation.neural.scales import ScaleSpec, estimate_parameters, scale
from generation.neural.three_d_latent import (
    GEOMETRY_CONTRACT,
    GeometryTokenSpec,
    PerEntityFieldDecoder,
)

__all__ = [
    "PipelineStage",
    "LagnavArchitecture",
    "LAGNAV_PIPELINE",
    "trace_pipeline",
]


@dataclass(frozen=True, slots=True)
class PipelineStage:
    """One stage of the proposed pipeline."""

    name: str
    role: str
    interface: str
    consumes: tuple[str, ...]
    produces: tuple[str, ...]
    contract: str
    implemented: bool = False
    trainable: bool = True
    notes: str | None = None

    def describe(self) -> str:
        """One-line human-readable description."""
        mark = "implemented" if self.implemented else "declared"
        return f"{self.name} [{mark}]: {self.role}"


LAGNAV_PIPELINE: tuple[PipelineStage, ...] = (
    PipelineStage(
        name="awr_features",
        role="Turn a validated AWR scene into index arrays, adjacency and state channels.",
        interface=AWRFeatureExtractor.__name__,
        consumes=(),
        produces=AWR_BATCH_CONTRACT.names(),
        contract="awr_batch",
        implemented=True,
        trainable=False,
        notes="Symbolic and exact. This stage is Step 4's output in tensor form.",
    ),
    PipelineStage(
        name="language_control",
        role="Map an utterance to an AWR program over the closed entity codebook.",
        interface=TextToProgramModel.__name__,
        consumes=("text_tokens", "text_mask", "entity_ids"),
        produces=PROGRAM_CONTRACT.names(),
        contract="awr_program",
        notes=(
            "Its supervision is generated by the Step 4 transcoder, which also remains a "
            "validator of its predictions."
        ),
    ),
    PipelineStage(
        name="language_conditioning",
        role="Pool the utterance into an embedding that conditions appearance only.",
        interface=ConditioningLanguageEncoder.__name__,
        consumes=("text_tokens", "text_mask"),
        produces=("text_hidden", "text_pooled"),
        contract="language_io",
        notes="Has no path to the AWR, so it cannot introduce or remove anatomy.",
    ),
    PipelineStage(
        name="graph_encoder",
        role="Contextualise entity latents over the structure, spatial and functional graphs.",
        interface=AnatomicalGraphEncoder.__name__,
        consumes=("entity_ids", "entity_type", "semantic_role", "laterality", "parent_index",
                  "depth", "edge_source", "edge_target", "edge_relation", "edge_graph",
                  "entity_mask", "edge_mask"),
        produces=("z_entity_out", "attention_mask", "relation_bias"),
        contract="graph_encoder_io",
        notes="Writes the context slice only; the identity slice passes through untouched.",
    ),
    PipelineStage(
        name="anatomical_encoder",
        role="Assemble the anatomical latent from symbols, context and conditioning.",
        interface=AnatomicalReasoningEncoder.__name__,
        consumes=("z_entity_out", "text_pooled", "active_lod", "educational_level", "entity_state"),
        produces=("z_scene", "z_entity", "z_relation", "entity_frame"),
        contract="anatomical_latent",
    ),
    PipelineStage(
        name="geometry_tokeniser",
        role="Produce a coarse-to-fine geometry token block per entity.",
        interface="GeometryTokenGenerator",
        consumes=("z_entity", "z_scene"),
        produces=("z_geometry",),
        contract="anatomical_latent",
        notes="Token order is nested, so a level of detail reads a prefix rather than a variant.",
    ),
    PipelineStage(
        name="field_decoder",
        role="Decode each entity's field in its canonical frame and attribute every point.",
        interface=PerEntityFieldDecoder.__name__,
        consumes=("z_geometry", "entity_frame", "entity_state", "query_points", "active_tokens"),
        produces=("entity_occupancy_logits", "scene_occupancy_logits", "part_logits"),
        contract="geometry_decoding",
        notes="Reads one entity's tokens at a time, which is what makes local editing local.",
    ),
    PipelineStage(
        name="alignment_heads",
        role="Project each modality into the shared anatomical alignment space.",
        interface=ModalityEncoder.__name__,
        consumes=("z_entity", "z_geometry", "text_pooled"),
        produces=("entity_prototypes", "align_text", "align_geometry"),
        contract="multimodal_alignment",
        notes="Optional at inference; required for training stages S0, S1 and S5.",
    ),
)
"""The proposed pipeline, in order."""


@dataclass(slots=True)
class LagnavArchitecture:
    """A composed, checkable description of the proposed model."""

    stages: tuple[PipelineStage, ...] = field(default_factory=lambda: LAGNAV_PIPELINE)
    scale_spec: ScaleSpec = field(default_factory=lambda: scale("prototype"))
    graph: GraphEncoderSpec = field(default_factory=GraphEncoderSpec)
    language: LanguageEncoderSpec = field(default_factory=LanguageEncoderSpec)
    geometry: GeometryTokenSpec = field(default_factory=GeometryTokenSpec)
    encoder: AnatomicalEncoderSpec = field(default_factory=AnatomicalEncoderSpec)
    status: str = "PROPOSED"

    def stage(self, name: str) -> PipelineStage:
        """Return one stage by name."""
        for candidate in self.stages:
            if candidate.name == name:
                return candidate
        raise ContractError(
            f"Unknown stage {name!r}. Declared: {', '.join(s.name for s in self.stages)}."
        )

    def contracts(self) -> tuple[Contract, ...]:
        """Every contract the pipeline touches, in stage order and without repeats."""
        seen: set[str] = set()
        out: list[Contract] = []
        for stage_spec in self.stages:
            if stage_spec.contract in seen:
                continue
            seen.add(stage_spec.contract)
            out.append(CONTRACTS.get(stage_spec.contract))
        return tuple(out)

    def validate(self, *, supplied: Sequence[str] = ()) -> None:
        """Check every stage's inputs are produced upstream or supplied with the batch.

        ``supplied`` names tensors that come from the training loop rather than
        from a stage, such as tokenised text and sampled query points.
        """
        available = set(supplied)
        for stage_spec in self.stages:
            missing = sorted(name for name in stage_spec.consumes if name not in available)
            if missing:
                raise ContractError(
                    f"Stage {stage_spec.name!r} consumes {missing}, which no earlier stage "
                    "produces and the batch does not supply."
                )
            available.update(stage_spec.produces)

    def parameter_estimate(
        self, vocabulary_sizes: Mapping[str, int] | None = None
    ) -> dict[str, int]:
        """Estimated parameters per component at the configured scale."""
        return estimate_parameters(self.scale_spec, vocabulary_sizes)

    def implemented_stages(self) -> tuple[str, ...]:
        """Stages that exist today."""
        return tuple(s.name for s in self.stages if s.implemented)

    def declared_stages(self) -> tuple[str, ...]:
        """Stages that are interfaces only."""
        return tuple(s.name for s in self.stages if not s.implemented)

    def summary(self) -> dict[str, object]:
        """Compact description for reports and tests."""
        return {
            "status": self.status,
            "scale": self.scale_spec.name,
            "stages": len(self.stages),
            "implemented": list(self.implemented_stages()),
            "declared": list(self.declared_stages()),
            "contracts": [contract.name for contract in self.contracts()],
        }


DEFAULT_SUPPLIED_TENSORS: tuple[str, ...] = (
    "text_tokens",
    "text_mask",
    "query_points",
    "entity_query_points",
    "active_tokens",
    "alignment_target",
    "align_image",
    "scene_lod",
    "scene_level",
)
"""Tensors the training loop supplies rather than a stage producing them."""


def trace_pipeline(
    scene: AWRScene,
    ontology: AnatomyOntology,
    *,
    architecture: LagnavArchitecture | None = None,
    batch_size: int = 2,
    query_points: int = 1024,
) -> dict[str, object]:
    """Run a shape-level pass of the whole pipeline from a real AWR scene.

    This is the architecture's smoke test. The first stage runs for real: an
    actual heart scene becomes contract-valid feature arrays. Every later stage is
    traced symbolically, resolving each declared output shape under one consistent
    set of dimension bindings.

    Returns a report naming, per stage, the tensors it produces and their resolved
    shapes, plus the bindings that held across the whole pipeline.
    """
    model = architecture or LagnavArchitecture()
    extractor = AWRFeatureExtractor(ontology)
    payload: dict[str, PlainArray] = extractor.encode_batch([scene] * batch_size)
    bindings = AWR_BATCH_CONTRACT.validate_payload(payload, bindings={"B": batch_size})
    bindings["P_QUERY"] = query_points
    bindings["N_CODEBOOK"] = len(extractor.codebook)

    model.validate(supplied=(*DEFAULT_SUPPLIED_TENSORS, *AWR_BATCH_CONTRACT.names()))

    known_contracts = (
        AWR_BATCH_CONTRACT,
        PROGRAM_CONTRACT,
        TEXT_CONTRACT,
        GRAPH_ENCODER_CONTRACT,
        LATENT_CONTRACT,
        SCENE_CONTEXT_CONTRACT,
        GEOMETRY_CONTRACT,
        ALIGNMENT_CONTRACT,
    )
    lookup = {contract.name: contract for contract in known_contracts}

    traced: dict[str, dict[str, tuple[int, ...]]] = {}
    for stage_spec in model.stages:
        contract = lookup[stage_spec.contract]
        shapes: dict[str, tuple[int, ...]] = {}
        for tensor_name in stage_spec.produces:
            try:
                spec = contract.spec(tensor_name)
            except ContractError:
                continue
            shapes[tensor_name] = spec.resolve(bindings)
        traced[stage_spec.name] = shapes

    return {
        "batch_size": batch_size,
        "bindings": dict(sorted(bindings.items())),
        "stages": traced,
        "real_tensors": {name: array.shape for name, array in sorted(payload.items())},
        "parameters": model.parameter_estimate(extractor.vocabulary_sizes()),
        "summary": model.summary(),
    }
